/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TraceabilityRouteImport } from './routes/traceability'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as PodRouteImport } from './routes/pod'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as OrgRouteImport } from './routes/org'
import { Route as OrchestrationRouteImport } from './routes/orchestration'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as EconomicsRouteImport } from './routes/economics'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CommsRouteImport } from './routes/comms'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as SettingsRolesRouteImport } from './routes/settings_.roles'
import { Route as PodsNewRouteImport } from './routes/pods.new'
import { Route as ApprovalsGateIdRouteImport } from './routes/approvals_.$gateId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const PodRoute = PodRouteImport.update({
  id: '/pod',
  path: '/pod',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrationRoute = OrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicsRoute = EconomicsRouteImport.update({
  id: '/economics',
  path: '/economics',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommsRoute = CommsRouteImport.update({
  id: '/comms',
  path: '/comms',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/settings_/roles',
  path: '/settings/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const PodsNewRoute = PodsNewRouteImport.update({
  id: '/pods/new',
  path: '/pods/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsGateIdRoute = ApprovalsGateIdRouteImport.update({
  id: '/approvals_/$gateId',
  path: '/approvals/$gateId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/artifacts': typeof ArtifactsRoute
  '/billing': typeof BillingRoute
  '/catalog': typeof CatalogRoute
  '/comms': typeof CommsRoute
  '/compliance': typeof ComplianceRoute
  '/connections': typeof ConnectionsRoute
  '/economics': typeof EconomicsRoute
  '/flow': typeof FlowRoute
  '/governance': typeof GovernanceRoute
  '/incidents': typeof IncidentsRoute
  '/intake': typeof IntakeRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/notifications': typeof NotificationsRoute
  '/observability': typeof ObservabilityRoute
  '/orchestration': typeof OrchestrationRoute
  '/org': typeof OrgRoute
  '/pilot': typeof PilotRoute
  '/pipeline': typeof PipelineRoute
  '/pitch': typeof PitchRoute
  '/pod': typeof PodRoute
  '/registry': typeof RegistryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/traceability': typeof TraceabilityRoute
  '/welcome': typeof WelcomeRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/approvals/$gateId': typeof ApprovalsGateIdRoute
  '/pods/new': typeof PodsNewRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/share/$token': typeof ShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/artifacts': typeof ArtifactsRoute
  '/billing': typeof BillingRoute
  '/catalog': typeof CatalogRoute
  '/comms': typeof CommsRoute
  '/compliance': typeof ComplianceRoute
  '/connections': typeof ConnectionsRoute
  '/economics': typeof EconomicsRoute
  '/flow': typeof FlowRoute
  '/governance': typeof GovernanceRoute
  '/incidents': typeof IncidentsRoute
  '/intake': typeof IntakeRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/notifications': typeof NotificationsRoute
  '/observability': typeof ObservabilityRoute
  '/orchestration': typeof OrchestrationRoute
  '/org': typeof OrgRoute
  '/pilot': typeof PilotRoute
  '/pipeline': typeof PipelineRoute
  '/pitch': typeof PitchRoute
  '/pod': typeof PodRoute
  '/registry': typeof RegistryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/traceability': typeof TraceabilityRoute
  '/welcome': typeof WelcomeRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/approvals/$gateId': typeof ApprovalsGateIdRoute
  '/pods/new': typeof PodsNewRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/share/$token': typeof ShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/artifacts': typeof ArtifactsRoute
  '/billing': typeof BillingRoute
  '/catalog': typeof CatalogRoute
  '/comms': typeof CommsRoute
  '/compliance': typeof ComplianceRoute
  '/connections': typeof ConnectionsRoute
  '/economics': typeof EconomicsRoute
  '/flow': typeof FlowRoute
  '/governance': typeof GovernanceRoute
  '/incidents': typeof IncidentsRoute
  '/intake': typeof IntakeRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/notifications': typeof NotificationsRoute
  '/observability': typeof ObservabilityRoute
  '/orchestration': typeof OrchestrationRoute
  '/org': typeof OrgRoute
  '/pilot': typeof PilotRoute
  '/pipeline': typeof PipelineRoute
  '/pitch': typeof PitchRoute
  '/pod': typeof PodRoute
  '/registry': typeof RegistryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/traceability': typeof TraceabilityRoute
  '/welcome': typeof WelcomeRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/approvals_/$gateId': typeof ApprovalsGateIdRoute
  '/pods/new': typeof PodsNewRoute
  '/settings_/roles': typeof SettingsRolesRoute
  '/share/$token': typeof ShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/approvals'
    | '/artifacts'
    | '/billing'
    | '/catalog'
    | '/comms'
    | '/compliance'
    | '/connections'
    | '/economics'
    | '/flow'
    | '/governance'
    | '/incidents'
    | '/intake'
    | '/knowledge'
    | '/login'
    | '/memory'
    | '/notifications'
    | '/observability'
    | '/orchestration'
    | '/org'
    | '/pilot'
    | '/pipeline'
    | '/pitch'
    | '/pod'
    | '/registry'
    | '/reports'
    | '/settings'
    | '/status'
    | '/traceability'
    | '/welcome'
    | '/agents/$agentId'
    | '/approvals/$gateId'
    | '/pods/new'
    | '/settings/roles'
    | '/share/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/approvals'
    | '/artifacts'
    | '/billing'
    | '/catalog'
    | '/comms'
    | '/compliance'
    | '/connections'
    | '/economics'
    | '/flow'
    | '/governance'
    | '/incidents'
    | '/intake'
    | '/knowledge'
    | '/login'
    | '/memory'
    | '/notifications'
    | '/observability'
    | '/orchestration'
    | '/org'
    | '/pilot'
    | '/pipeline'
    | '/pitch'
    | '/pod'
    | '/registry'
    | '/reports'
    | '/settings'
    | '/status'
    | '/traceability'
    | '/welcome'
    | '/agents/$agentId'
    | '/approvals/$gateId'
    | '/pods/new'
    | '/settings/roles'
    | '/share/$token'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/approvals'
    | '/artifacts'
    | '/billing'
    | '/catalog'
    | '/comms'
    | '/compliance'
    | '/connections'
    | '/economics'
    | '/flow'
    | '/governance'
    | '/incidents'
    | '/intake'
    | '/knowledge'
    | '/login'
    | '/memory'
    | '/notifications'
    | '/observability'
    | '/orchestration'
    | '/org'
    | '/pilot'
    | '/pipeline'
    | '/pitch'
    | '/pod'
    | '/registry'
    | '/reports'
    | '/settings'
    | '/status'
    | '/traceability'
    | '/welcome'
    | '/agents/$agentId'
    | '/approvals_/$gateId'
    | '/pods/new'
    | '/settings_/roles'
    | '/share/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ApprovalsRoute: typeof ApprovalsRoute
  ArtifactsRoute: typeof ArtifactsRoute
  BillingRoute: typeof BillingRoute
  CatalogRoute: typeof CatalogRoute
  CommsRoute: typeof CommsRoute
  ComplianceRoute: typeof ComplianceRoute
  ConnectionsRoute: typeof ConnectionsRoute
  EconomicsRoute: typeof EconomicsRoute
  FlowRoute: typeof FlowRoute
  GovernanceRoute: typeof GovernanceRoute
  IncidentsRoute: typeof IncidentsRoute
  IntakeRoute: typeof IntakeRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  NotificationsRoute: typeof NotificationsRoute
  ObservabilityRoute: typeof ObservabilityRoute
  OrchestrationRoute: typeof OrchestrationRoute
  OrgRoute: typeof OrgRoute
  PilotRoute: typeof PilotRoute
  PipelineRoute: typeof PipelineRoute
  PitchRoute: typeof PitchRoute
  PodRoute: typeof PodRoute
  RegistryRoute: typeof RegistryRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  TraceabilityRoute: typeof TraceabilityRoute
  WelcomeRoute: typeof WelcomeRoute
  ApprovalsGateIdRoute: typeof ApprovalsGateIdRoute
  PodsNewRoute: typeof PodsNewRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pod': {
      id: '/pod'
      path: '/pod'
      fullPath: '/pod'
      preLoaderRoute: typeof PodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestration': {
      id: '/orchestration'
      path: '/orchestration'
      fullPath: '/orchestration'
      preLoaderRoute: typeof OrchestrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economics': {
      id: '/economics'
      path: '/economics'
      fullPath: '/economics'
      preLoaderRoute: typeof EconomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comms': {
      id: '/comms'
      path: '/comms'
      fullPath: '/comms'
      preLoaderRoute: typeof CommsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/roles': {
      id: '/settings_/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pods/new': {
      id: '/pods/new'
      path: '/pods/new'
      fullPath: '/pods/new'
      preLoaderRoute: typeof PodsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals_/$gateId': {
      id: '/approvals_/$gateId'
      path: '/approvals/$gateId'
      fullPath: '/approvals/$gateId'
      preLoaderRoute: typeof ApprovalsGateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ApprovalsRoute: ApprovalsRoute,
  ArtifactsRoute: ArtifactsRoute,
  BillingRoute: BillingRoute,
  CatalogRoute: CatalogRoute,
  CommsRoute: CommsRoute,
  ComplianceRoute: ComplianceRoute,
  ConnectionsRoute: ConnectionsRoute,
  EconomicsRoute: EconomicsRoute,
  FlowRoute: FlowRoute,
  GovernanceRoute: GovernanceRoute,
  IncidentsRoute: IncidentsRoute,
  IntakeRoute: IntakeRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  NotificationsRoute: NotificationsRoute,
  ObservabilityRoute: ObservabilityRoute,
  OrchestrationRoute: OrchestrationRoute,
  OrgRoute: OrgRoute,
  PilotRoute: PilotRoute,
  PipelineRoute: PipelineRoute,
  PitchRoute: PitchRoute,
  PodRoute: PodRoute,
  RegistryRoute: RegistryRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  TraceabilityRoute: TraceabilityRoute,
  WelcomeRoute: WelcomeRoute,
  ApprovalsGateIdRoute: ApprovalsGateIdRoute,
  PodsNewRoute: PodsNewRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
