/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraceabilityRouteImport } from './routes/traceability'
import { Route as PodRouteImport } from './routes/pod'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OrchestrationRouteImport } from './routes/orchestration'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as EconomicsRouteImport } from './routes/economics'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CommsRouteImport } from './routes/comms'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'

const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)
const PodRoute = PodRouteImport.update({
  id: '/pod',
  path: '/pod',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrationRoute = OrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicsRoute = EconomicsRouteImport.update({
  id: '/economics',
  path: '/economics',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommsRoute = CommsRouteImport.update({
  id: '/comms',
  path: '/comms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/comms': typeof CommsRoute
  '/compliance': typeof ComplianceRoute
  '/economics': typeof EconomicsRoute
  '/flow': typeof FlowRoute
  '/governance': typeof GovernanceRoute
  '/knowledge': typeof KnowledgeRoute
  '/observability': typeof ObservabilityRoute
  '/orchestration': typeof OrchestrationRoute
  '/pipeline': typeof PipelineRoute
  '/pod': typeof PodRoute
  '/traceability': typeof TraceabilityRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/comms': typeof CommsRoute
  '/compliance': typeof ComplianceRoute
  '/economics': typeof EconomicsRoute
  '/flow': typeof FlowRoute
  '/governance': typeof GovernanceRoute
  '/knowledge': typeof KnowledgeRoute
  '/observability': typeof ObservabilityRoute
  '/orchestration': typeof OrchestrationRoute
  '/pipeline': typeof PipelineRoute
  '/pod': typeof PodRoute
  '/traceability': typeof TraceabilityRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/comms': typeof CommsRoute
  '/compliance': typeof ComplianceRoute
  '/economics': typeof EconomicsRoute
  '/flow': typeof FlowRoute
  '/governance': typeof GovernanceRoute
  '/knowledge': typeof KnowledgeRoute
  '/observability': typeof ObservabilityRoute
  '/orchestration': typeof OrchestrationRoute
  '/pipeline': typeof PipelineRoute
  '/pod': typeof PodRoute
  '/traceability': typeof TraceabilityRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/approvals'
    | '/comms'
    | '/compliance'
    | '/economics'
    | '/flow'
    | '/governance'
    | '/knowledge'
    | '/observability'
    | '/orchestration'
    | '/pipeline'
    | '/pod'
    | '/traceability'
    | '/agents/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/approvals'
    | '/comms'
    | '/compliance'
    | '/economics'
    | '/flow'
    | '/governance'
    | '/knowledge'
    | '/observability'
    | '/orchestration'
    | '/pipeline'
    | '/pod'
    | '/traceability'
    | '/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/approvals'
    | '/comms'
    | '/compliance'
    | '/economics'
    | '/flow'
    | '/governance'
    | '/knowledge'
    | '/observability'
    | '/orchestration'
    | '/pipeline'
    | '/pod'
    | '/traceability'
    | '/agents/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ApprovalsRoute: typeof ApprovalsRoute
  CommsRoute: typeof CommsRoute
  ComplianceRoute: typeof ComplianceRoute
  EconomicsRoute: typeof EconomicsRoute
  FlowRoute: typeof FlowRoute
  GovernanceRoute: typeof GovernanceRoute
  KnowledgeRoute: typeof KnowledgeRoute
  ObservabilityRoute: typeof ObservabilityRoute
  OrchestrationRoute: typeof OrchestrationRoute
  PipelineRoute: typeof PipelineRoute
  PodRoute: typeof PodRoute
  TraceabilityRoute: typeof TraceabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pod': {
      id: '/pod'
      path: '/pod'
      fullPath: '/pod'
      preLoaderRoute: typeof PodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestration': {
      id: '/orchestration'
      path: '/orchestration'
      fullPath: '/orchestration'
      preLoaderRoute: typeof OrchestrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economics': {
      id: '/economics'
      path: '/economics'
      fullPath: '/economics'
      preLoaderRoute: typeof EconomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comms': {
      id: '/comms'
      path: '/comms'
      fullPath: '/comms'
      preLoaderRoute: typeof CommsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ApprovalsRoute: ApprovalsRoute,
  CommsRoute: CommsRoute,
  ComplianceRoute: ComplianceRoute,
  EconomicsRoute: EconomicsRoute,
  FlowRoute: FlowRoute,
  GovernanceRoute: GovernanceRoute,
  KnowledgeRoute: KnowledgeRoute,
  ObservabilityRoute: ObservabilityRoute,
  OrchestrationRoute: OrchestrationRoute,
  PipelineRoute: PipelineRoute,
  PodRoute: PodRoute,
  TraceabilityRoute: TraceabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
