/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraceabilityRouteImport } from './routes/traceability'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PodRouteImport } from './routes/pod'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OrchestrationRouteImport } from './routes/orchestration'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as EconomicsRouteImport } from './routes/economics'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CommsRouteImport } from './routes/comms'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PodsNewRouteImport } from './routes/pods.new'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'

const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PodRoute = PodRouteImport.update({
  id: '/pod',
  path: '/pod',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrationRoute = OrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicsRoute = EconomicsRouteImport.update({
  id: '/economics',
  path: '/economics',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommsRoute = CommsRouteImport.update({
  id: '/comms',
  path: '/comms',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodsNewRoute = PodsNewRouteImport.update({
  id: '/pods/new',
  path: '/pods/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/billing': typeof BillingRoute
  '/catalog': typeof CatalogRoute
  '/comms': typeof CommsRoute
  '/compliance': typeof ComplianceRoute
  '/connections': typeof ConnectionsRoute
  '/economics': typeof EconomicsRoute
  '/flow': typeof FlowRoute
  '/governance': typeof GovernanceRoute
  '/incidents': typeof IncidentsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/observability': typeof ObservabilityRoute
  '/orchestration': typeof OrchestrationRoute
  '/pipeline': typeof PipelineRoute
  '/pod': typeof PodRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/traceability': typeof TraceabilityRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/pods/new': typeof PodsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/billing': typeof BillingRoute
  '/catalog': typeof CatalogRoute
  '/comms': typeof CommsRoute
  '/compliance': typeof ComplianceRoute
  '/connections': typeof ConnectionsRoute
  '/economics': typeof EconomicsRoute
  '/flow': typeof FlowRoute
  '/governance': typeof GovernanceRoute
  '/incidents': typeof IncidentsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/observability': typeof ObservabilityRoute
  '/orchestration': typeof OrchestrationRoute
  '/pipeline': typeof PipelineRoute
  '/pod': typeof PodRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/traceability': typeof TraceabilityRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/pods/new': typeof PodsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/billing': typeof BillingRoute
  '/catalog': typeof CatalogRoute
  '/comms': typeof CommsRoute
  '/compliance': typeof ComplianceRoute
  '/connections': typeof ConnectionsRoute
  '/economics': typeof EconomicsRoute
  '/flow': typeof FlowRoute
  '/governance': typeof GovernanceRoute
  '/incidents': typeof IncidentsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/observability': typeof ObservabilityRoute
  '/orchestration': typeof OrchestrationRoute
  '/pipeline': typeof PipelineRoute
  '/pod': typeof PodRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/traceability': typeof TraceabilityRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/pods/new': typeof PodsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/approvals'
    | '/billing'
    | '/catalog'
    | '/comms'
    | '/compliance'
    | '/connections'
    | '/economics'
    | '/flow'
    | '/governance'
    | '/incidents'
    | '/knowledge'
    | '/login'
    | '/observability'
    | '/orchestration'
    | '/pipeline'
    | '/pod'
    | '/reports'
    | '/settings'
    | '/traceability'
    | '/agents/$agentId'
    | '/pods/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/approvals'
    | '/billing'
    | '/catalog'
    | '/comms'
    | '/compliance'
    | '/connections'
    | '/economics'
    | '/flow'
    | '/governance'
    | '/incidents'
    | '/knowledge'
    | '/login'
    | '/observability'
    | '/orchestration'
    | '/pipeline'
    | '/pod'
    | '/reports'
    | '/settings'
    | '/traceability'
    | '/agents/$agentId'
    | '/pods/new'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/approvals'
    | '/billing'
    | '/catalog'
    | '/comms'
    | '/compliance'
    | '/connections'
    | '/economics'
    | '/flow'
    | '/governance'
    | '/incidents'
    | '/knowledge'
    | '/login'
    | '/observability'
    | '/orchestration'
    | '/pipeline'
    | '/pod'
    | '/reports'
    | '/settings'
    | '/traceability'
    | '/agents/$agentId'
    | '/pods/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ApprovalsRoute: typeof ApprovalsRoute
  BillingRoute: typeof BillingRoute
  CatalogRoute: typeof CatalogRoute
  CommsRoute: typeof CommsRoute
  ComplianceRoute: typeof ComplianceRoute
  ConnectionsRoute: typeof ConnectionsRoute
  EconomicsRoute: typeof EconomicsRoute
  FlowRoute: typeof FlowRoute
  GovernanceRoute: typeof GovernanceRoute
  IncidentsRoute: typeof IncidentsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  ObservabilityRoute: typeof ObservabilityRoute
  OrchestrationRoute: typeof OrchestrationRoute
  PipelineRoute: typeof PipelineRoute
  PodRoute: typeof PodRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TraceabilityRoute: typeof TraceabilityRoute
  PodsNewRoute: typeof PodsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pod': {
      id: '/pod'
      path: '/pod'
      fullPath: '/pod'
      preLoaderRoute: typeof PodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestration': {
      id: '/orchestration'
      path: '/orchestration'
      fullPath: '/orchestration'
      preLoaderRoute: typeof OrchestrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economics': {
      id: '/economics'
      path: '/economics'
      fullPath: '/economics'
      preLoaderRoute: typeof EconomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comms': {
      id: '/comms'
      path: '/comms'
      fullPath: '/comms'
      preLoaderRoute: typeof CommsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pods/new': {
      id: '/pods/new'
      path: '/pods/new'
      fullPath: '/pods/new'
      preLoaderRoute: typeof PodsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ApprovalsRoute: ApprovalsRoute,
  BillingRoute: BillingRoute,
  CatalogRoute: CatalogRoute,
  CommsRoute: CommsRoute,
  ComplianceRoute: ComplianceRoute,
  ConnectionsRoute: ConnectionsRoute,
  EconomicsRoute: EconomicsRoute,
  FlowRoute: FlowRoute,
  GovernanceRoute: GovernanceRoute,
  IncidentsRoute: IncidentsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  ObservabilityRoute: ObservabilityRoute,
  OrchestrationRoute: OrchestrationRoute,
  PipelineRoute: PipelineRoute,
  PodRoute: PodRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TraceabilityRoute: TraceabilityRoute,
  PodsNewRoute: PodsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
